"""
Skout — Idea Card Generator
Creates a structured, shareable one-pager from answers + research findings.
Gated: requires minimum research completion before unlocking.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from datetime import date
from typing import Any, Dict, List, Optional

from .scoring_engine import VerdictResult


@dataclass
class IdeaCard:
    title: str
    description: str
    domain: str
    problem: str
    primary_stakeholder: str
    current_state: str
    verdict_score: float
    verdict_label: str
    verdict_emoji: str
    origin: str
    origin_multiplier: float
    date_created: str
    hypothesis: str
    validated_evidence: List[str]
    key_adoption_risk: str
    proposed_direction: str
    open_questions: List[str]
    next_actions: List[str]
    research_status: str   # "not_started" | "in_progress" | "complete"
    confidence_flags: List[str] = field(default_factory=list)

    def to_markdown(self) -> str:
        """Export idea card as Markdown."""
        lines = [
            f"# {self.title}",
            f"> {self.description}",
            "",
            f"**Domain:** {self.domain}  |  **Verdict:** {self.verdict_emoji} {self.verdict_score}/100 — {self.verdict_label}  |  **Date:** {self.date_created}",
            "",
            "---",
            "",
            "## Problem Statement",
            self.problem,
            "",
            "## Primary User",
            self.primary_stakeholder,
            "",
            "## Current State",
            self.current_state,
            "",
            "## Hypothesis",
            self.hypothesis,
            "",
            "## Validated Evidence",
        ]
        for e in self.validated_evidence:
            lines.append(f"- {e}")
        lines += [
            "",
            "## Key Adoption Risk",
            self.key_adoption_risk,
            "",
            "## Proposed Direction",
            self.proposed_direction,
            "",
            "## Open Questions",
        ]
        for q in self.open_questions:
            lines.append(f"- {q}")
        lines += [
            "",
            "## Next Actions",
        ]
        for a in self.next_actions:
            lines.append(f"- [ ] {a}")
        lines += ["", "---", f"*Generated by Skout · {self.date_created}*"]
        return "\n".join(lines)

    def to_dict(self) -> Dict:
        return {
            "title": self.title,
            "description": self.description,
            "domain": self.domain,
            "problem": self.problem,
            "primary_stakeholder": self.primary_stakeholder,
            "current_state": self.current_state,
            "verdict_score": self.verdict_score,
            "verdict_label": self.verdict_label,
            "verdict_emoji": self.verdict_emoji,
            "origin": self.origin,
            "origin_multiplier": self.origin_multiplier,
            "date_created": self.date_created,
            "hypothesis": self.hypothesis,
            "validated_evidence": self.validated_evidence,
            "key_adoption_risk": self.key_adoption_risk,
            "proposed_direction": self.proposed_direction,
            "open_questions": self.open_questions,
            "next_actions": self.next_actions,
            "research_status": self.research_status,
        }


class IdeaCardGenerator:
    """
    Generates an IdeaCard from completed answers + logged research findings.

    Gate: minimum_criteria must be satisfied before generation is allowed.
    """

    GATE_MINIMUM_CRITERIA = 2   # at least N success criteria checked
    GATE_MINIMUM_FINDINGS = 1   # at least N research findings logged

    DOMAIN_LABELS = {
        "planning": "Planning & Forecasting",
        "procurement": "Procurement & Sourcing",
        "repair": "Repair & MRO",
        "trade": "Trade & Compliance",
        "fraud": "Fraud & Risk",
    }
    STAKEHOLDER_LABELS = {
        "sc_planners": "Supply Chain Planners",
        "procurement_mgrs": "Procurement / Category Managers",
        "operations": "Operations / Field Teams",
        "finance": "Finance & Compliance",
        "leadership": "Leadership / C-suite",
        "external_partners": "External Partners",
    }
    CURRENT_STATE_LABELS = {
        "manual_spreadsheet": "Manual / spreadsheet-driven — no real tooling",
        "legacy_erp": "Legacy ERP (SAP/Oracle) — insufficient for this problem",
        "siloed_tools": "Siloed point solutions — multiple disconnected tools",
        "competitor_exists": "Competitor product exists — market served but poorly",
        "internal_tool": "Internal tool exists but not scalable",
        "not_handled": "Not handled at all — problem is ignored",
    }
    ORIGIN_LABELS = {
        "user_reported_many": "User-reported (20+ users)",
        "user_reported_several": "User-reported (2–19 users)",
        "user_reported_one": "User-reported (1 user)",
        "usage_data": "Observed in usage data/analytics",
        "partner_feedback": "Partner/supplier feedback",
        "pm_hypothesis": "Internal PM hypothesis",
        "competitive_intel": "Competitive intelligence",
        "leadership_directive": "Leadership directive",
    }

    def check_gate(
        self,
        checked_criteria: List[bool],
        findings: List[str],
    ) -> tuple[bool, str]:
        """
        Returns (unlocked: bool, reason: str).
        checked_criteria: list of booleans from success criteria checkboxes.
        findings: list of non-empty finding strings logged by the user.
        """
        criteria_met = sum(1 for c in checked_criteria if c)
        findings_met = sum(1 for f in findings if f and f.strip())

        if criteria_met < self.GATE_MINIMUM_CRITERIA:
            return False, (
                f"Check at least {self.GATE_MINIMUM_CRITERIA} success criteria "
                f"(currently {criteria_met}/{len(checked_criteria)})"
            )
        if findings_met < self.GATE_MINIMUM_FINDINGS:
            return False, (
                f"Log at least {self.GATE_MINIMUM_FINDINGS} research finding "
                f"(currently {findings_met} logged)"
            )
        return True, "Gate passed — Idea Card ready to generate"

    def generate(
        self,
        answers: Dict[str, Any],
        verdict: VerdictResult,
        idea_title: str,
        idea_description: str,
        research_plan: Dict,
        findings: List[str],
        proposed_direction: str = "",
        open_questions: Optional[List[str]] = None,
    ) -> IdeaCard:
        """Build an IdeaCard from all available data."""
        domain = answers.get("q1", "")
        q5 = answers.get("q5", {}) or {}

        # Derive validated evidence from findings + quantified criteria
        evidence = [f for f in findings if f and f.strip()]

        # Derive open questions from research plan if not provided
        if not open_questions:
            open_questions = self._derive_open_questions(answers, research_plan)

        # Default proposed direction if not entered
        if not proposed_direction:
            proposed_direction = (
                f"A solution that addresses {answers.get('q2', 'the core problem')} "
                f"for {self.STAKEHOLDER_LABELS.get(answers.get('q3', ''), 'the primary user')}, "
                f"working with or above existing {self.CURRENT_STATE_LABELS.get(answers.get('q4', ''), 'tooling')}."
            )

        # Next actions from verdict band
        next_actions = verdict.next_steps[:3] if verdict.next_steps else [
            "Validate findings with an additional 2 stakeholders",
            "Define success metrics before writing the spec",
            "Share this card with your engineering lead",
        ]

        # Research status
        if not findings:
            r_status = "not_started"
        elif len(findings) >= 3:
            r_status = "complete"
        else:
            r_status = "in_progress"

        return IdeaCard(
            title=idea_title or "Untitled Idea",
            description=idea_description or "",
            domain=self.DOMAIN_LABELS.get(domain, domain),
            problem=answers.get("q2", ""),
            primary_stakeholder=self.STAKEHOLDER_LABELS.get(answers.get("q3", ""), answers.get("q3", "")),
            current_state=self.CURRENT_STATE_LABELS.get(answers.get("q4", ""), answers.get("q4", "")),
            verdict_score=verdict.final_score,
            verdict_label=verdict.band_label,
            verdict_emoji=verdict.band_emoji,
            origin=self.ORIGIN_LABELS.get(answers.get("origin", ""), answers.get("origin", "")),
            origin_multiplier=verdict.origin_multiplier,
            date_created=str(date.today()),
            hypothesis=research_plan.get("hypothesis", ""),
            validated_evidence=evidence,
            key_adoption_risk=self._derive_adoption_risk(research_plan, answers),
            proposed_direction=proposed_direction,
            open_questions=open_questions,
            next_actions=next_actions,
            research_status=r_status,
            confidence_flags=[f["message"] for f in verdict.confidence_flags],
        )

    def _derive_open_questions(self, answers: Dict, research_plan: Dict) -> List[str]:
        """Generate open questions from research plan and answers."""
        domain = answers.get("q1", "")
        domain_questions = {
            "planning": [
                "What is the minimum forecast accuracy improvement users would need before switching tools?",
                "How does the planning problem vary across different product categories or regions?",
                "Who owns the forecast KPI — demand planning or commercial?",
            ],
            "procurement": [
                "What's the minimum PO-invoice match accuracy needed before procurement trusts automation?",
                "Does the solution need to integrate with supplier invoicing systems, or just ingest PDFs?",
                "Who owns the exception queue — procurement or AP? This determines where the UI lives.",
            ],
            "repair": [
                "Is the bottleneck in parts ordering, parts logistics, or technician capacity?",
                "How does parts counterfeit risk vary across product categories?",
                "Who makes the decision to approve a repair vs. replace — and what data do they need?",
            ],
            "trade": [
                "Which trade corridors generate the most compliance exceptions?",
                "Is the primary driver customs clearance time or documentation accuracy?",
                "What is the regulatory risk appetite of the compliance team?",
            ],
            "fraud": [
                "What detection latency is acceptable — real-time vs. end-of-cycle?",
                "Who has authority to halt a payment based on a fraud flag?",
                "What evidence threshold is required before escalating a fraud case internally?",
            ],
        }
        return domain_questions.get(domain, [
            "Who will own this solution long-term — product, IT, or operations?",
            "What does 'done' look like in 6 months?",
            "What existing system integrations are non-negotiable?",
        ])

    def _derive_adoption_risk(self, research_plan: Dict, answers: Dict) -> str:
        """Extract key adoption risk from research plan or derive from domain."""
        if research_plan.get("riskiest_assumption"):
            return research_plan["riskiest_assumption"]
        domain = answers.get("q1", "")
        risks = {
            "planning": "Data quality from upstream systems — if the input data is unreliable, planners won't trust the output.",
            "procurement": "Supplier data format inconsistency — invoice structures vary widely and any solution must handle dirty inputs.",
            "repair": "Field technician adoption — depot staff are resistant to new tools if they add steps to an already pressured workflow.",
            "trade": "Regulatory change risk — any automated compliance logic must be updatable as trade regulations change.",
            "fraud": "False positive rate — if the system flags too many legitimate transactions, it will be bypassed or ignored.",
        }
        return risks.get(domain, "User trust and change management — adoption requires more than a good product.")
