"""
Integrations — Phase 5
Export adapters: Notion markdown blocks, Jira issue JSON, generic webhook POST, CSV.
Also supports Team Mode: shared idea pool via data/team_ideas.json.
"""
from __future__ import annotations

import csv
import io
import json
import urllib.request
import urllib.error
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any, Dict, List, Optional


# ------------------------------------------------------------------ #
# Notion export
# ------------------------------------------------------------------ #

def to_notion_markdown(card_dict: Dict) -> str:
    """
    Generate a Notion-compatible markdown representation of an IdeaCard.
    Notion imports markdown with its own block format.
    """
    title  = card_dict.get("title", "Untitled Idea")
    score  = card_dict.get("verdict_score", 0)
    domain = card_dict.get("domain", "")
    date_  = card_dict.get("date_created", str(date.today()))
    emoji  = card_dict.get("verdict_emoji", "")

    lines = [
        f"# {emoji} {title}",
        f"> **Domain:** {domain}  |  **Score:** {int(score)}/100  |  **Date:** {date_}",
        "",
        "---",
        "",
        "## 📌 Problem",
        card_dict.get("problem", ""),
        "",
        "## 👤 Primary User",
        card_dict.get("primary_stakeholder", ""),
        "",
        "## 🗺️ Current State",
        card_dict.get("current_state", ""),
        "",
        "## 💡 Proposed Direction",
        card_dict.get("proposed_direction", "_Not yet defined_"),
        "",
        "---",
        "",
        "## 🔬 Hypothesis",
        f"> {card_dict.get('hypothesis', '')}",
        "",
        "---",
        "",
        "## ✅ Validated Evidence",
    ]
    for e in (card_dict.get("validated_evidence") or []):
        lines.append(f"- {e}")
    if not card_dict.get("validated_evidence"):
        lines.append("_No findings logged yet_")

    lines += [
        "",
        "## ⚠️ Key Adoption Risk",
        card_dict.get("key_adoption_risk", ""),
        "",
        "## ❓ Open Questions",
    ]
    for q in (card_dict.get("open_questions") or []):
        if q.strip():
            lines.append(f"- {q}")

    lines += [
        "",
        "## ▶️ Next Actions",
    ]
    for a in (card_dict.get("next_actions") or []):
        lines.append(f"- [ ] {a}")

    lines += [
        "",
        "---",
        f"_Generated by Product Skout · Supply Chain Edition_",
    ]
    return "\n".join(lines)


# ------------------------------------------------------------------ #
# Jira export
# ------------------------------------------------------------------ #

def to_jira_issue(card_dict: Dict, project_key: str = "SC") -> Dict:
    """
    Generate a Jira issue creation payload (REST API v3 format).
    POST to: /rest/api/3/issue
    """
    title  = card_dict.get("title", "Untitled Idea")
    score  = card_dict.get("verdict_score", 0)
    domain = card_dict.get("domain", "")
    band   = card_dict.get("verdict_label", "")

    description_text = "\n\n".join([
        f"*Problem:* {card_dict.get('problem', '')}",
        f"*Primary User:* {card_dict.get('primary_stakeholder', '')}",
        f"*Current State:* {card_dict.get('current_state', '')}",
        f"*Proposed Direction:* {card_dict.get('proposed_direction', 'TBD')}",
        f"*Hypothesis:* {card_dict.get('hypothesis', '')}",
        "",
        "*Validated Evidence:*",
        "\n".join(f"- {e}" for e in (card_dict.get("validated_evidence") or [])) or "_None yet_",
        "",
        "*Key Adoption Risk:*",
        card_dict.get("key_adoption_risk", ""),
        "",
        "*Next Actions:*",
        "\n".join(f"- {a}" for a in (card_dict.get("next_actions") or [])),
        "",
        f"_Skout score: {int(score)}/100 — {band} — {domain}_",
    ])

    priority = (
        "Highest" if score >= 80 else
        "High"    if score >= 60 else
        "Medium"  if score >= 40 else
        "Low"
    )

    return {
        "fields": {
            "project":     {"key": project_key},
            "summary":     f"[Skout] {title} (score: {int(score)}/100)",
            "description": {
                "type":    "doc",
                "version": 1,
                "content": [
                    {
                        "type": "paragraph",
                        "content": [{"type": "text", "text": description_text}]
                    }
                ],
            },
            "issuetype":   {"name": "Story"},
            "priority":    {"name": priority},
            "labels":      ["skout", f"domain-{domain}", f"band-{card_dict.get('verdict_label','').lower().replace(' ','-')}"],
        }
    }


def to_jira_json_str(card_dict: Dict, project_key: str = "SC") -> str:
    return json.dumps(to_jira_issue(card_dict, project_key), indent=2)


# ------------------------------------------------------------------ #
# CSV export
# ------------------------------------------------------------------ #

def to_csv(card_dicts: List[Dict]) -> str:
    """
    Convert a list of idea card dicts to CSV string.
    Works for both a single card (list of 1) or a portfolio.
    """
    if not card_dicts:
        return ""

    fieldnames = [
        "title", "domain", "verdict_score", "verdict_label",
        "date_created", "origin", "primary_stakeholder",
        "current_state", "research_status", "proposed_direction",
    ]

    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=fieldnames, extrasaction="ignore")
    writer.writeheader()
    for d in card_dicts:
        writer.writerow({k: d.get(k, "") for k in fieldnames})
    return output.getvalue()


# ------------------------------------------------------------------ #
# Generic webhook POST
# ------------------------------------------------------------------ #

@dataclass
class WebhookResult:
    success: bool
    status_code: Optional[int] = None
    response_body: str = ""
    error: str = ""


def post_webhook(
    url: str,
    payload: Dict,
    headers: Optional[Dict[str, str]] = None,
    timeout: int = 10,
) -> WebhookResult:
    """
    POST a JSON payload to the given URL.
    Returns a WebhookResult with success flag and response info.
    No external dependencies — uses urllib.
    """
    if not url or not url.startswith(("http://", "https://")):
        return WebhookResult(success=False, error="Invalid URL — must start with http:// or https://")

    try:
        body = json.dumps(payload).encode("utf-8")
        req_headers = {"Content-Type": "application/json", "User-Agent": "ProductSkout/1.0"}
        if headers:
            req_headers.update(headers)

        req = urllib.request.Request(url, data=body, headers=req_headers, method="POST")
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            resp_body = resp.read().decode("utf-8", errors="replace")[:500]
            return WebhookResult(success=True, status_code=resp.status, response_body=resp_body)

    except urllib.error.HTTPError as e:
        return WebhookResult(success=False, status_code=e.code, error=str(e))
    except urllib.error.URLError as e:
        return WebhookResult(success=False, error=f"Connection error: {e.reason}")
    except Exception as e:
        return WebhookResult(success=False, error=str(e))


def build_webhook_payload(card_dict: Dict, extra_fields: Optional[Dict] = None) -> Dict:
    """Build a clean webhook payload from an idea card dict."""
    payload = {
        "event":       "skout.idea_card.generated",
        "timestamp":   date.today().isoformat(),
        "idea": {
            "title":           card_dict.get("title", ""),
            "domain":          card_dict.get("domain", ""),
            "score":           card_dict.get("verdict_score", 0),
            "band":            card_dict.get("verdict_label", ""),
            "origin":          card_dict.get("origin", ""),
            "research_status": card_dict.get("research_status", ""),
        },
    }
    if extra_fields:
        payload.update(extra_fields)
    return payload


# ------------------------------------------------------------------ #
# Team Mode — shared idea pool
# ------------------------------------------------------------------ #

TEAM_IDEAS_PATH = str(Path(__file__).parent.parent / "data" / "team_ideas.json")


def _ensure_team_file(path: str = TEAM_IDEAS_PATH):
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    if not p.exists():
        p.write_text("[]", encoding="utf-8")


def get_team_ideas(team_id: str = "default", path: str = TEAM_IDEAS_PATH) -> List[Dict]:
    """Load shared team ideas for the given team_id."""
    _ensure_team_file(path)
    try:
        with open(path, "r", encoding="utf-8") as f:
            all_ideas = json.load(f)
        return [i for i in all_ideas if i.get("team_id", "default") == team_id]
    except (FileNotFoundError, json.JSONDecodeError):
        return []


def share_to_team(card_dict: Dict, author_name: str, team_id: str = "default", path: str = TEAM_IDEAS_PATH) -> bool:
    """
    Add an idea card to the shared team pool.
    Returns True if added, False if already shared (by title + team_id).
    """
    _ensure_team_file(path)
    try:
        with open(path, "r", encoding="utf-8") as f:
            all_ideas = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        all_ideas = []

    # Dedup check
    existing_titles = {
        i.get("title", "").strip().lower()
        for i in all_ideas if i.get("team_id") == team_id
    }
    if card_dict.get("title", "").strip().lower() in existing_titles:
        return False

    entry = {
        "team_id":      team_id,
        "author":       author_name,
        "shared_date":  date.today().isoformat(),
        "title":        card_dict.get("title", ""),
        "domain":       card_dict.get("domain", ""),
        "score":        card_dict.get("verdict_score", 0),
        "band":         card_dict.get("verdict_label", ""),
        "hypothesis":   card_dict.get("hypothesis", ""),
        "next_actions": card_dict.get("next_actions", []),
        "research_status": card_dict.get("research_status", "not_started"),
        "comments":     [],
    }
    all_ideas.append(entry)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(all_ideas, f, indent=2, ensure_ascii=False)
    return True


def add_team_comment(idea_title: str, author: str, comment: str, team_id: str = "default", path: str = TEAM_IDEAS_PATH) -> bool:
    """Add a comment to a shared team idea."""
    _ensure_team_file(path)
    try:
        with open(path, "r", encoding="utf-8") as f:
            all_ideas = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return False

    for idea in all_ideas:
        if (idea.get("team_id") == team_id and
                idea.get("title", "").strip().lower() == idea_title.strip().lower()):
            idea.setdefault("comments", []).append({
                "author":  author,
                "text":    comment[:500],
                "date":    date.today().isoformat(),
            })
            with open(path, "w", encoding="utf-8") as f:
                json.dump(all_ideas, f, indent=2, ensure_ascii=False)
            return True
    return False
